#!/bin/bash

set -e

# dependecies: at
# put lines like these to you /etc/hosts
# 127.0.0.1	mail.google.com	# BLOCKME
# It is necessary that user can use sudo without typing password.

# -i means inplace (instead of piping)
sudo sed -i -r '/BLOCKME/s/^#[# ]+//g' /etc/hosts

echo "Good choice!"
echo "Don't forget to determine conditions for unblocking."

# removing all at jobs. TODO: filter out only block_communications
# at -c 211 will show content given script
for i in `atq | awk '{print $1}'`;do atrm $i;done

# logging:
date '+%Y-%m-%d %H:%M:%S block' >> ~/.block_communications.log
